2023-10-16 19:08:16,339 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2023-10-16 19:08:16,353 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'ssh']
2023-10-16 19:08:16,356 DEBUG    root            Running [gcloud.compute.ssh] with arguments: [[USER@]INSTANCE: "instances"]
2023-10-16 19:08:16,451 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2023-10-16 19:08:17,409 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/nghiawarden/zones/us-west1-b/instances/instances?alt=json HTTP/1.1" 404 None
2023-10-16 19:08:17,411 DEBUG    root            Chosen display Format:list[title="Could not fetch resource:",always-display-title]
2023-10-16 19:08:17,411 DEBUG    root            (gcloud.compute.ssh) Could not fetch resource:
 - The resource 'projects/nghiawarden/zones/us-west1-b/instances/instances' was not found
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/compute/ssh.py", line 286, in Run
    instance = ssh_helper.GetInstance(client, instance_ref)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/ssh_utils.py", line 533, in GetInstance
    return client.MakeRequests([request])[0]
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 156, in MakeRequests
    utils.RaiseToolException(
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 139, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 148, in RaiseException
    raise exception(
googlecloudsdk.calliope.exceptions.ToolException: Could not fetch resource:
 - The resource 'projects/nghiawarden/zones/us-west1-b/instances/instances' was not found

2023-10-16 19:08:17,412 ERROR    root            (gcloud.compute.ssh) Could not fetch resource:
 - The resource 'projects/nghiawarden/zones/us-west1-b/instances/instances' was not found

